### ISSUE TITLE
Multiple HMMFiles

### ISSUE THREAD

**Issue by zdk123** [althonos/pyhmmer#24]
This is related to issue #23, but rather having multiple HMMs in a single file, I'd like to treat the HMMs across multiple files as a single iterable to `hmmsearch`. This would reduce the overall memory footprint (again, similar to the motivations discussed #23).

Here's a wrapper class that does the trick and also works as a context manager:
```py
from pyhmmer.plan7 import HMMFile
from itertools import chain

class HMMFiles():
    def __init__(self, files):
        self.hmmfiles = [HMMFile(f) for f in files]

    def __enter__(self):
        return chain.from_iterable(self.hmmfiles)

    def __exit__(self, *args):
        for f in self.hmmfiles:
            f.close()
```

Usage:
```py
with pyhmmer.easel.SequenceFile('queries.fasta') as seq_file, HMMFiles(['1.hmm', '2.hmm']) as hmm_file:
    hits = list(pyhmmer.hmmsearch(hmm_file, list(sequences)))
```

Thought I would leave this here for posterity even if it doesn't fit in the repo.

**Comment by althonos** [comment]
This is actually a neat trick; if I don't include it to the code, I'll definitely add it to the documentation!

**Comment by althonos** [comment]
This is now in the documentation since `v0.7.4` :smiley:

**Comment by chtsai0105** [comment]
Hi - I have a related question about the loading multiple HMM files.

I'm working on a tool that use pyhmmer hmmsearch module to find orthologs among several sequences against the busco dataset. It worked great when searching against the fungi_odb10 dataset (contains 758 markers). But when I tested with mammalia_odb10 (with 9,226 markers) and vertebrata_odb10 (with 3,354 markers) markersets, a file not found error occurred even that file do exist.

I did a bunch of test and found that the file not found error always occurred on the 1020th markers. And later I realize it might be related to the system constrain. Many of the system limit a user to open up to 1024 files at the same time. (according to cmd `ulimit -a`)

Although might not be directly related to your package, do you have any suggestion about opening up to 1024 files through the context manager? Or is that possible to keep the HMM information after close the file?
