### ISSUE TITLE
hmmsearch gathering/trusted/noise cutoffs doesn't apply to single domains (i.e., --domT)

### ISSUE THREAD

**Issue by satriaphd** [althonos/pyhmmer#26]
in the original HMMsearch, when using --cut_ga, cutoffs are applied both to the sequences (-T) and each single domain (--domT), as exampled below:

![image](https://user-images.githubusercontent.com/7368871/202248319-fccdb931-2e95-482c-b664-94fad17e1ae9.png)

in pyHMMer, each single domain hits were still retained even if they don't pass the bitscore cutoff (in this case, 21.4)

![image](https://user-images.githubusercontent.com/7368871/202249081-042532f8-903e-403a-9a39-a3a41933f2d7.png)

**Comment by satriaphd** [comment]
note: I was able to still filter the domains by comparing the best_domain vs the tophits' domT attribute (thanks for that, really neat to be able to refer back to the pHMM models from the results), but I was just wondering if this feature is intended (e.g., so you can still see what the individual hits are)

**Comment by althonos** [comment]
Hi @satriaphd 

This is actually a good question! I'll have to check internally how HMMER handles this; I suspect it's as you say that all the domains are kept in the hit even when under the cutoff, and then filtered out in the display. In that case, I would probably add `Domain.is_included` and `Domain.is_reported` methods like the `Hit` objects have, to make this more idiomatic.

**Comment by althonos** [comment]
As I thought, the domains are treated like the hits, and kept in the list even when they don't meet inclusion/reporting thresholds. I'm improving the way it's handled in `v0.7.0` to make that more intuitive.

**Comment by althonos** [comment]
You can now iterate only on selected domains with:
```python
for top_hits in pyhmmer.hmmsearch(hmm_file, sequences, cpus=1, bit_cutoffs="gathering"):
    for hit in top_hits.included:
        print("hit--")
        print("sequence score: {}".format(hit.score))
        print("domain scores: {}".format([dom.score for dom in hit.domains.included]))
```
which is equivalent to:
```python
for top_hits in pyhmmer.hmmsearch(hmm_file, sequences, cpus=1, bit_cutoffs="gathering"):
    for hit in top_hits:
        if hit.included:
            print("hit--")
            print("sequence score: {}".format(hit.score))
            print("domain scores: {}".format([dom.score for dom in hit.domains if domain.included]))
```
