### ISSUE TITLE
build hmm from multiple sequence alignment

### ISSUE THREAD

**Issue by tijeco** [althonos/pyhmmer#3]
Is there any way to use hmmbuild through pyhmmer to build hmm models from multiple sequence alignment files?

**Comment by althonos** [comment]
Hi @tijeco !

At the moment this is not supported, but it's high on the TO-DO list :smile:

**Comment by althonos** [comment]
Hi @tijeco ,

the `master` branch now has code that let you build HMMs from multiple sequence alignments. This is how you could get it to work:
```python
import pyhmmer

abc = pyhmmer.easel.Alphabet.dna()
builder = pyhmmer.plan7.Builder(alphabet=abc)

with pyhmmer.easel.MSAFile("alignment.sto") as msa_file:
    msa_file.set_digital(abc)
    msa = next(msa_file)

# MSA must have a name, otherwise building will fail
if msa.name is None:
    msa.name = b"alignment"

hmm, _, _ = builder.build_msa(msa, Background(abc))
```

**Comment by tijeco** [comment]
Wow! That was quick! I'll give it a try!

Thanks for all your hard work on pyhmmer, it's a great tool that will certainly be useful for my research.

**Comment by althonos** [comment]
You should have all you need to work in `v0.3.0`, which I just released. I also added an example to the documentation: https://pyhmmer.readthedocs.io/en/v0.3.0/examples/msa_to_hmm.html

Glad you find the library useful! I'll be closing this issue, but you can comment here if you have some more questions about this. Cheer!

**Comment by tijeco** [comment]
@althonos  I am having a weird issue getting this to work with the alignment file in the documentation (I've attached it here in case something strange happened to the formatting, github required me to add a .txt ending). 
[test.sto.txt](https://github.com/althonos/pyhmmer/files/6160413/test.sto.txt)
I run the following 

```python
with pyhmmer.easel.MSAFile("test.sto") as msa_file:
    msa_file.set_digital(abc)
    msa = next(msa_file)

# MSA must have a name, otherwise building will fail
if msa.name is None:
    msa.name = b"alignment"

hmm, _, _ = builder.build_msa(msa, Background(abc))
```

But I get this error.  

```
ValueError                                Traceback (most recent call last)
<ipython-input-8-0aeecaefab24> in <module>
      5 with pyhmmer.easel.MSAFile("data/test.sto") as msa_file:
      6     msa_file.set_digital(abc)
----> 7     msa = next(msa_file)
      8 
      9 # MSA must have a name, otherwise building will fail

~/miniconda3/envs/duomolog/lib/python3.8/site-packages/pyhmmer/easel.pyx in pyhmmer.easel.MSAFile.__next__()

~/miniconda3/envs/duomolog/lib/python3.8/site-packages/pyhmmer/easel.pyx in pyhmmer.easel.MSAFile.read()

ValueError: Could not parse file: invalid sequence character(s) on line
```

I'm using pyhmmer v0.3.0 from conda

Are there invalid sequence characters that I am unaware of?

**Comment by althonos** [comment]
@tijeco : your alignment is a protein sequence, so you need to use `Alphabet.amino()` instead of `Alphabet.dna()`, the example I gave was for a DNA sequence :)

**Comment by tijeco** [comment]
Thanks so much! I knew it had to be something silly that I was missing.
