### ISSUE TITLE
search_hmm with --cut-ga

### ISSUE THREAD

**Issue by willhuynh11** [althonos/pyhmmer#32]
Hello,

Thanks in advance for the help.
Just wondering how I can use the search_hmm from 
https://pyhmmer.readthedocs.io/en/stable/api/plan7.html#pyhmmer.plan7.TopHits
with --cut-ga or equivalent.

**Comment by althonos** [comment]
Hi @willhuynh11 

You can use the `hmmsearch` and `hmmscan` functions directly or use the `Pipeline.search_hmm` method with the `bit_cutoffs` keyword argument:
```python
pyhmmer.hmmsearch(hmms, sequences, bit_cutoffs="gathering")
```
(similarly for `"trusted"` and `"noise"` cutoffs)

**Comment by althonos** [comment]
Hopefully this answers your question, feel free to reopen a new issue if you have other problems.
