### ISSUE TITLE
Generating sequences

### ISSUE THREAD

**Issue by mireklzicar** [althonos/pyhmmer#39]
Is it possible to generate sequences based on the hmm profile transition probabilities? (e.g. sample from the alphabet based on the vocabulary)

**Comment by althonos** [comment]
Hi @mireklzicar, at the moment there is no way to do this from either HMMER or PyHMMER I think. However, it should be possible to implement in Python, given that you have access to the emission scores and transition probabilities of the HMMs, so you could walk the HMM states and sample like you suggest.
