### ISSUE TITLE
search_hmm finds 0 hits

### ISSUE THREAD

**Issue by GiancarloCroce** [althonos/pyhmmer#4]
Hi! Thanks for your tool, It's very useful to have a Python interface to HMMER.

I'm having some problems with search_hmm.
I can reproduce the example in the Documentation with LuxC.hmm and LuxC.faa, but when using different hmm models search_hmm does not find any hit. 

I'm using  the MHC_I.hmm model (downloaded from http://pfam.xfam.org/family/PF00129/hmm) and  a set of sequences belonging to the same domain (downloaded from http://pfam.xfam.org/family/PF00129#tabview=tab3,  RP15 with no gaps). 
Running hmmserach from the terminal I find exactly one hit for each sequence (as expected), but pipeline.search_hmm doesn't find any

Here my code to reproduce the error: 
```pyhton3
#load hmm                                                                                                                                                                         
path_hmm = './test/MHC_I.hmm'                                                                                                                                                                 
hmm_file = pyhmmer.plan7.HMMFile(path_hmm)                                                                                                                                                    
hmm = next(hmm_file)                                                                                                                                                                          
#pipeline                                                                                                                                                                                     
alphabet = pyhmmer.easel.Alphabet.amino()                                                                                                                                                     
background = pyhmmer.plan7.Background(alphabet)                                                                                                                                               
pipeline = pyhmmer.plan7.Pipeline(alphabet, background=background, report_e=1e-5)                                                                                                             
#apply hmm to a sequence dataset                                                                                                                                                              
seq_file = pyhmmer.easel.SequenceFile("./test/PF00129_rp15.faa")                                                                                                                              
seq_file.set_digital(alphabet)                                                                                                                                                                
hits = pipeline.search_hmm(query=hmm, sequences=seq_file) 
len(hits) = 0
```

Am I missing something?
Thanks!

**Comment by althonos** [comment]
Hi @GiancarloCroce !

I cannot reproduce locally, after running your script I get 387 hits, as expected. At least, that means your code is correct :)
What is your platform, and are you running the latest version of the library?

**Comment by GiancarloCroce** [comment]
Thanks for your answer! 
I'm running pyhmmer  v. 0.3.0 on a x86_64 GNU/Linux. I installed it with pip. I've also tried to clone the repository and run the setup.py file manually, but still 0 hits.

**Comment by althonos** [comment]
Does it change anything if you set the `report_e` to a different value?

**Comment by GiancarloCroce** [comment]
Hi,
I solved it! When parsing my target sequence db ("./test/PF00129_rp15.faa") I did a mistake, and the output was not a fasta file.  The script runs smoothly now, and I get 387 hits !
Thanks for your help! I knew it was something stupid :)

**Comment by althonos** [comment]
Great ! It happens :)
