### ISSUE TITLE
Error while running nhmmer

### ISSUE THREAD

**Issue by theabhirath** [althonos/pyhmmer#42]
Hello! I am trying to use this package for searching DNA queries against a sequence database, and I am running into an error I am unable to debug. I am running the function `pyhmmer.hmmer.nhmmer(msa, sequences, cpus=1)` and am encountering the following error - `TypeError: Cannot convert pyhmmer.easel.DigitalMSA to pyhmmer.easel.DigitalSequence`.

Further, when I convert the `msa` to an `hmm` and pass it to the function, I get a different error: `UnexpectedError: Unexpected error occurred in 'idlen_list_assign': eslENOTFOUND (status code 6)`.

The code I am running is given below. I am running it on Google Colab:

```python
import pyhmmer

alphabet = pyhmmer.easel.Alphabet.dna()

with pyhmmer.easel.MSAFile("output.msa", digital=True, alphabet=alphabet) as msa_file:
    msa = msa_file.read()

msa.name = b"output_mafft"

builder = pyhmmer.plan7.Builder(alphabet)
background = pyhmmer.plan7.Background(alphabet)
hmm, _, _ = builder.build_msa(msa, background)

with pyhmmer.easel.SequenceFile("all.fasta", digital=True) as seq_file:
    sequences = seq_file.read_block()

hits = next(pyhmmer.hmmer.nhmmer(msa, sequences, cpus=1)) # or hmm instead of msa
```

I am attaching the MSA file and the FASTA sequence file herewith. Could you please help me understand what could be going wrong? Thank you! (PS: the MSA is of type aligned FASTA and was created using `mafft`, in case that is useful information.)

[nhmmer.zip](https://github.com/althonos/pyhmmer/files/11650944/nhmmer.zip)

**Comment by althonos** [comment]
Hi @theabhirath , thanks a lot for the detailed report, I'll have a look. It could be a bug in HMMER given the error you're getting, so I appreciate that you included the resources to reproduce :wink:

**Comment by theabhirath** [comment]
Thanks for the prompt response, I loved your package and hope to be using the new release soon! 😁
