### ISSUE TITLE
`incE` not being respected

### ISSUE THREAD

**Issue by EvanKomp** [althonos/pyhmmer#43]
pyhmmer vs 0.8.1

Running `hmmscan` on some proteins vs Pfam.

eg.
```
seqs = pyhmmer.easel.SequenceFile('test.fasta', format='fasta', digital=True, alphabet=pyhmmer.easel.Alphabet.amino())
targets = pyhmmer.plan7.HMMFile('Pfam.hmm')
all_hits = pyhmmer.hmmer.hmmscan(seqs, targets, cpus=cpu, incE=eval_con)
```

The following then raises:
```
for top_hits in all_hits:
    for hit in top_hits:
        assert hit.evalue < top_hits.incE
```

LMK if inclusion of additional info would help.

EDIT: If this filtering happens in python, I am happy to find it and make a pull, though if its down in the cython I will have a hard time :(

**Comment by althonos** [comment]
Hi Evan! By default, the `TopHits` returned by a `hmmsearch` or `hmmscan` contain all hits under the _reporting_ threshold, which is independent (and usually higher) than the _inclusion_ threshold. To only get hits under the inclusion threshold, use:
```python
for top_hits in all_hits:
    for hit in top_hits.included:
        assert hit.evalue < top_hits.incE
```
which is a shortcut for:
```python
for top_hits in all_hits:
    for hit in top_hits:
        if hit.included:
            assert hit.evalue < top_hits.incE

**Comment by EvanKomp** [comment]
❤️
