### ISSUE TITLE
Batch the hmmsearch output

### ISSUE THREAD

**Issue by chtsai0105** [althonos/pyhmmer#51]
Hi - I'm wondering if it is possible to return the hmmsearch results by batch?

As the size of the result isn't directly calculable based on the size of the input/database, but rather depending on the number of matches discovered, out-of-memory errors may arise when matches continuously expand, eventually reach the maximum memory I've set initially.

Is it possible to batch the output results, enabling me to extract the necessary information and then save it to disk?

**Comment by althonos** [comment]
HI @chtsai0105,

`hmmsearch` by default is already returning an iterator, so you can start saving the results and discarding them as soon as they are available. If you have memory issues it may be that you cannot process them fast enough and that new hits accumulate in the background.

To batch the output, you can just batch the input! With `hmmsearch`, the results should be consistent independently of the way the queries are batched. For instance:

```python
import pyhmmer
import itertools

with pyhmmer.easel.SequenceFile("pyhmmer/tests/data/seqs/938293.PRJEB85.HG003687.faa", digital=True) as seq_file:
    for batch_id in itertools.count():
        block = seq_file.read_block(sequences=100)
        if not block:
            break
        with pyhmmer.plan7.HMMFile("pyhmmer/tests/data/hmms/txt/t2pks.hmm") as hmm_file:
            for hits in pyhmmer.hmmsearch(hmm_file, block, cpus=4):
                print(f"HMM {hits.query_name.decode()} found {len(hits)} hits in batch {batch_id}")
```

In this example, the sequence file is processed 100 sequences at a time. The small disadvantage is that you need to reload the HMMs every time, so you could actually store them in a list (If you have enough memory) to avoid the I/O:

```python
import pyhmmer
import itertools

with pyhmmer.plan7.HMMFile("pyhmmer/tests/data/hmms/txt/t2pks.hmm") as hmm_file:
    hmms = list(hmm_file)

with pyhmmer.easel.SequenceFile("pyhmmer/tests/data/seqs/938293.PRJEB85.HG003687.faa", digital=True) as seq_file:
    for batch_id in itertools.count():
        block = seq_file.read_block(sequences=100)
        if not block:
            break
        for hits in pyhmmer.hmmsearch(hmms, block, cpus=4):
            print(f"HMM {hits.query_name.decode()} found {len(hits)} hits in batch {batch_id}")
```

**Comment by chtsai0105** [comment]
Thank you for the examples!

Now I just realized that the major memory bottleneck might be how I store the results. I'm using a similar structure described [here](https://pyhmmer.readthedocs.io/en/stable/examples/fetchmgs.html#Loading-the-sequences) to store the results. I guess for a very big dataset/hmm markerset, using a list might not be good choice. As the results accumulated it eventually will hit the memory limitation. Using batch input probably not able to fix this unless I write the output periodically to a temp file or use a generator to process the output directly.

I'll try to come up with a solution and update it here as a recommendation to store results for a big dataset.

**Comment by althonos** [comment]
Indeed, each `Alignment` from HMMER uses around 2kiB of memory to store the rendered alignment. Since you can have one `Alignment` per `Domain`, several `Domain` per `Hit`, and several `Hit` for each query `HMM` this can add up quickly! If you're only interested in the alignment coordinates, or the hit per HMM, you could just extract that while hmmsearch is running.

**Comment by chtsai0105** [comment]
Finally resolved the memory issue by combining batch inputs and use generator to send the results for further processing. Just want to leave a note for a reference.

In my case I have to gather all the hits for each individual sequence (gene) and remove the overlapped hits. Hmmsearch actually searches all the sequences against a hmm profile for each round, so I need to wait until all searches are completed to get the matches for each individual sequence and do further processing. Previously I was also using [a similar structure as GECCO](https://github.com/chtsai0105/dbcanLight/blob/a9dca42c6586aae1dc7370462f879de650b509dc/src/dbcanlight/dbcanlight.py#L24-L80) to save the results, but it will still crash when processing a file containing over a million of sequences.

Inspiring by the examples you provided, I [batch the inputs](https://github.com/chtsai0105/dbcanLight/blob/main/src/dbcanlight/dbcanlight.py#L76-L86), do all the [post-processing on this batch](https://github.com/chtsai0105/dbcanLight/blob/main/src/dbcanlight/hmmsearch_parser.py#L74-L107), and directly output it. By doing so I can control the memory consumption on the sequence block size.

I'm closing the issue. Thanks for you help once again!

**Comment by althonos** [comment]
Glad it works! :+1:
