### ISSUE TITLE
Is it possible to get/apply cutoffs?

### ISSUE THREAD

**Issue by zdk123** [althonos/pyhmmer#9]
From the code it looks like it should be possible to obtain the PFAM gathering/noise/trusted cutoffs from the HMM class 
e.g.
https://github.com/althonos/pyhmmer/blob/master/pyhmmer/plan7.pyx#L623
https://github.com/althonos/pyhmmer/blob/master/pyhmmer/plan7.pyx#L2259
https://github.com/althonos/pyhmmer/blob/master/pyhmmer/plan7.pyi#L218

However:
```py
from pyhmmer.plan7 import HMMFile, HMM

with HMMFile("path/to/Pfam-A.hmm") as hmms:
   hmm = next(hmms)

dir(hmm) ## I don't see any attributes that seem to correspond to cutoffs
```

Is there any way to obtain the cutoffs or, even better, apply the cutoff in a search_hmm pipeline?

Using pyhmmer v0.4.5.

Thanks!

**Comment by althonos** [comment]
Hi Zachary,

I added support for viewing the cutoffs in the development version (the future `v0.4.6`), but it's not released yet. I'll add support for using the cutoffs in the `plan7.Pipeline` before releasing, too.

**Comment by althonos** [comment]
Just pushed `v0.4.6`, you can now get the cutoffs of a HMM with the [`HMM.cutoffs`](https://pyhmmer.readthedocs.io/en/v0.4.6/api/plan7.html#pyhmmer.plan7.HMM.cutoffs) property.

To use them in a search pipeline, pass either `"trusted"`, `"gathering"` or `"noise"` as a value to the `bit_cutoffs` keyword argument when creating a new `plan7.Pipeline`, or directly as a keyword argument to `pyhmmer.hmmer.hmmsearch`. Cheers!

**Comment by zdk123** [comment]
fantastic! thanks so much for adding this feature so quickly.
